telegram_token: "700...:AAH..."       # from @BotFather
tg_channel: "@yourRiskChannel"        # channel username
rpc_https: "https://solana-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
jupiter_quote: "https://quote-api.jup.ag/v6/quote"
jupiter_swap:  "https://quote-api.jup.ag/v6/swap"
bot_keypair: [170,231,...]             # 64-byte list
redis_url: "redis://localhost:6379/0"